#!/usr/bin/env python

import os
import re
import requests
import subprocess
import sys

command = sys.argv[1:]
if len(command) < 1:
    sys.stderr.write("no command to run, exiting\n")
    sys.exit(1)

server = os.environ.get("JOB_DB_SERVER", "https://job-db.kahawai.net.nz")
timeout = int(os.environ.get("JOB_DB_REQUEST_TIMEOUT", 60))

try:
    job_id = int(re.sub('^JobID ', '', os.environ.get("JOBID", "1000000")))
except:
    job_id = 1000000

token = None

if os.path.exists("/.webtoken") and os.path.getsize("/.webtoken") > 10:
    token = open("/.webtoken", "rt").read()

if not token:
    sys.stderr.write("No job token available; unable to request temporary database\n")
    sys.exit(1)

db_codes = {"read": []}

for var in os.environ.keys():
    if var.endswith("_BUILD"):
        db_codes["build"] = var.lower().strip().replace("_", "-")
        break

if "DATABASES" in os.environ:
    codes = [c.strip() for c in os.environ["DATABASES"].lower().replace("_", "-").split(",")]
    for code in codes:
        if code.endswith("-build"):
            if not "build" in db_codes:
                db_codes["build"] = code
            continue
        else:
            db_codes["read"].append(code)

post_data = db_codes.copy()
post_data["job_id"] = job_id
post_data["token"] = token
headers = {"Content-Type": "application/json"}

r = requests.post("%s/db/new" % server, json=post_data, headers=headers, timeout=timeout)

if r.status_code == 403:
    sys.stderr.write("Request for temporary database refused\n")
    sys.exit(1)

if r.status_code != 200:
    sys.stderr.write("Request for temporary database failed with status %d\n" % r.status_code)
    sys.exit(1)

temp_db = r.json().get("temp_db", {})

env = dict(os.environ)
env["KAHAWAI_DBNAME"] = temp_db.get("dbname")
env["KAHAWAI_DBUSER"] = temp_db.get("user")
env["KAHAWAI_DBPASS"] = temp_db.get("password")
env["KAHAWAI_DBHOST"] = temp_db.get("host")
env["KAHAWAI_DBPORT"] = temp_db.get("port")

building = r.json().get("build", None)
if building:
    sys.stderr.write("Building %s database\n" % building)
sys.stderr.write("Available databases: " + ", ".join(r.json().get("imported", [])) + "\n")

sys.stderr.write("Command: " + " ".join(command) + "\n")
sys.stderr.flush()

return_code = subprocess.Popen(command, env=env).wait()

post_data["temp_db"] = temp_db

if return_code == 0 and building:
    r = requests.post("%s/db/rename" % server, json=post_data, headers=headers, timeout=timeout)
else:
    r = requests.post("%s/db/delete" % server, json=post_data, headers=headers, timeout=timeout)

if r.status_code == 200:
    if "message" in r.json():
        sys.stderr.write(r.json().get("message") + "\n")
    sys.exit(return_code)
else:
    sys.exit(1)
