FROM docker.tridentsystems.co.nz/ubuntu/nz
MAINTAINER richard@dragonfly.co.nz

RUN apt-get update &&  \
    apt-get install --no-install-recommends -y \
                postgresql-client-9.5 openssh-client

