FROM docker.tridentsystems.co.nz/ubuntu/pisces

MAINTAINER richard@dragonfly.co.nz

RUN apt-get update &&  \
    apt-get install --no-install-recommends -y \
                postgresql-client openssh-client mysql-client

