FROM docker.tridentsystems.co.nz/ubuntu/gorbachev-base

MAINTAINER richard@dragonfly.co.nz

RUN apt-get update &&  \
    apt-get install --no-install-recommends -y \
    openssh-client mysql-client s3cmd

